### PR TITLE
update cargo binary path

### PR DESCRIPTION
**Pull request by Uniminin**

### CODE REVIEW

**Comment by Wafelack** [comment]
It has already been changed in the README (in [be16ee3](https://github.com/Wafelack/wng/commit/be16ee38a1dd55b711f8aa5bbcb105e2db956359) ). Thx for interesting in Wanager anyway.

**Comment by Uniminin** [comment]
@Wafelack I don't see those specific changes I've made!

**Comment by Wafelack** [comment]
I've removed the system specific formulation to just show the installation command

**Comment by Wafelack** [comment]
Ok my bad, i thought i commited my changes, but i didn't

**Comment by Wafelack** [comment]
Ok so fixed in [e1e0337](https://github.com/Wafelack/wng/commit/e1e03370cc524e9b809789c4a08629d72834cacf), and my apologies for the mistake

**Pull request closed without merging**
